; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:featheresp32]
; platform = espressif32
; board = featheresp32
; framework = arduino
; monitor_speed = 115200
; lib_deps = 
; 	adafruit/Adafruit EPD@^4.5.4
; 	adafruit/Adafruit GFX Library@^1.11.9
; 	adafruit/RTClib@^2.1.3
; 	bblanchon/ArduinoJson@^7.0.3
; 	adafruit/Adafruit ADT7410 Library@^1.3.1
; 	adafruit/Adafruit Unified Sensor@^1.1.14
; 	https://github.com/Lake-Tuggeranong-College/CyberCitySharedFunctionality
; 	knolleary/PubSubClient@^2.8


; The remainder of the file is for use with the 
; ESP32-S3 with TFT

[env:adafruit_feather_esp32s3_reversetft]
platform = espressif32
board = adafruit_feather_esp32s3_reversetft
framework = arduino

; Serial Monitor Setup
monitor_speed = 115200

; Native USB Configuration for ESP32-S3
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; Required Libraries
lib_deps = 
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit GFX Library@^1.11.9
	adafruit/RTClib@^2.1.3
	bblanchon/ArduinoJson@^7.0.3
	adafruit/Adafruit ADT7410 Library@^1.3.1
	adafruit/Adafruit Unified Sensor@^1.1.14